export const site = {
  name: "Grandcabin · Turufjell",
  language: "nb",
  description:
    "En romslig fjellhytte på Turufjell med 29 sengeplasser, ni soverom, to badstuer og ski inn/ut.",
};

export const finnUrl =
  "https://www.finn.no/reise/feriehus-hytteutleie/ad.html?finnkode=333328013";

export const photos = [
  "exterior",
  "living",
  "dining",
  "terrace",
  "gathering",
  "sauna",
  "bedroom",
  "ski",
  "cycling",
];

export const copy = {
  nb: {
    nav: ["Hytta", "Bilder", "Opplevelser"],
    cta: "Se hytta på FINN",
    skip: "Hopp til innhold",
    location: "TURUFJELL · FLÅ · HALLINGDAL",
    headline: ["Store øyeblikk.", "Sammen på fjellet."],
    hero: "Ta med hele gjengen til Turufjell. Her venter lange middager, lune kvelder og fjellet rett utenfor døren.",
    explore: "Oppdag hytta",
    photo: "Se bildene",
    scroll: "Senk skuldrene. Du er fremme.",
    stats: ["sengeplasser", "soverom", "kvadratmeter", "badstuer"],
    introLabel: "PLASS TIL Å VÆRE SAMMEN",
    introTitle: "Langt fra hverdagen.\nNær hverandre.",
    intro: "En av Turufjells mest særpregede hytter – og det er lett å forstå hvorfor. Gjennomtenkt arkitektur, solide materialer og høy komfort skaper rammene for et helt spesielt opphold.",
    intro2: "Hytta ble ferdigstilt i 2024 og har vannbåren varme i hele hytta og balansert ventilasjon. Samle storfamilien, vennegjengen eller kollegaene til gode dager i Hallingdal.",
    detail: "9 soverom · 4 bad · 2 kjøkken · 2 badstuer",
    galleryLabel: "ET LITE INNBLIKK",
    galleryTitle: "Finn din favorittplass.",
    galleryText: "Fra morgenkaffen ved vinduet til den siste praten foran peisen.",
    allPhotos: "Alle 75 bilder på FINN",
    open: "Åpne bilde",
    close: "Lukk",
    previous: "Forrige bilde",
    next: "Neste bilde",
    captions: [
      "En varm velkomst på Turufjell",
      "Stuen i hovedetasjen",
      "Samles rundt bordet",
      "Terrassen",
      "Plass til hele gjengen",
      "Badstuen i hovedetasjen",
      "Et rom for hvile",
      "Vinter på Turufjell",
      "På to hjul i fjellet",
    ],
    comfortLabel: "HYTTELIV, MED LITT EKSTRA",
    comfortTitle: "Alt ligger til rette.",
    comforts: [
      ["Ski fra døren", "Langrennsløypa starter rett utenfor hytta, og alpinanlegget nås på ski etter omtrent 150 meter – helt uten bil."],
      ["Varme etter turen", "To badstuer, varme i gulvene og ved til peisen. Finn roen etter en dag i frisk fjelluft."],
      ["De lange måltidene", "To kjøkken og langbord med plass til 14–16 i hovedetasjen og 26–28 i underetasjen."],
      ["Samle kollegaene", "Plass til møter, kurs og teambuilding. Bredbånd og romslige fellesarealer gjør samlingen enkel."],
    ],
    amenities: ["Wi-Fi", "Parkering", "4 oppvaskmaskiner", "Vaskemaskin", "TV", "Grill", "Barneseng og barnestol"],
    seasonsLabel: "ET FJELL. FIRE ÅRSTIDER.",
    seasonsTitle: "Ut i det fri.",
    winter: "Dager på ski",
    winterText: "Start dagen i langrennsløypa eller ta familien med i alpinbakken. Stopp innom kaféen ved bakken før turen går hjem til peisen.",
    summer: "Stier, sykkel og fjelluft",
    summerText: "Utforsk turstiene mot Kristnatten, prøv pumptracken eller finn roen ved et fiskevann. Her er det lett å fylle dagene ute.",
    locationLabel: "NÆRMERE ENN DU TROR",
    locationTitle: "Fjellfølelsen.\nUnder to timer fra Oslo.",
    locationText: "På solsiden av Turufjell, i Flå i Hallingdal, ligger hytta med utsikt over fjellandskapet. Omtrent 15 minutter med bil tar deg til Flå sentrum, butikker og Bjørneparken.",
    transport: "Du kan også ta tog til Flå og taxi videre til hytta. Det er god plass til parkering på eiendommen og elbillading ved kaféen nær skiheisen.",
    practical: "Godt å vite",
    practicalItems: [
      ["Hvor mange er det plass til?", "Hytta har opptil 29 sengeplasser fordelt på ni soverom og en sovealkove på loftet. Se romfordelingen og detaljene på FINN."],
      ["Hva gjelder for sengetøy og utvask?", "Sengetøy og håndklær kan ordnes etter avtale. Sluttrengjøring er obligatorisk. Se FINN-annonsen for gjeldende pris og vilkår."],
      ["Kan vi ta med kjæledyr?", "Kjæledyr og røyking er ikke tillatt. Hytta er ikke tilrettelagt for rullestol."],
      ["Hvordan sender vi en forespørsel?", "Gå til annonsen vår på FINN for å se ledige datoer, priser og leievilkår, og ta kontakt med utleier der."],
    ],
    endLabel: "DERES NESTE FJELLTUR",
    endTitle: "Gode minner\nbegynner her.",
    endText: "Finn en helg. Samle gjengen. Se ledige datoer og send en forespørsel på FINN.",
    endCta: "Se tilgjengelighet på FINN",
    footer: "En hytte for de store øyeblikkene.",
    source: "Informasjon og bilder fra vår FINN-annonse.",
  },
  en: {
    nav: ["The cabin", "Gallery", "Experiences"],
    cta: "View on FINN",
    skip: "Skip to content",
    location: "TURUFJELL · FLÅ · HALLINGDAL",
    headline: ["Big moments.", "Together in the mountains."],
    hero: "Bring everyone to Turufjell. Long dinners, cosy evenings and the mountains just outside your door.",
    explore: "Explore the cabin",
    photo: "View photos",
    scroll: "Take a breath. You’ve arrived.",
    stats: ["beds", "bedrooms", "square metres", "saunas"],
    introLabel: "ROOM TO COME TOGETHER",
    introTitle: "Away from the everyday.\nCloser to each other.",
    intro: "One of Turufjell’s most distinctive cabins – and it is easy to see why. Thoughtful architecture, quality materials and modern comfort come together for a truly special stay.",
    intro2: "Completed in 2024, the cabin has hydronic heating throughout and balanced ventilation. Bring your extended family, friends or colleagues for a mountain getaway in Hallingdal.",
    detail: "9 bedrooms · 4 bathrooms · 2 kitchens · 2 saunas",
    galleryLabel: "TAKE A LOOK INSIDE",
    galleryTitle: "Find your favourite corner.",
    galleryText: "From morning coffee by the window to one last conversation by the fire.",
    allPhotos: "All 75 photos on FINN",
    open: "Open photo",
    close: "Close",
    previous: "Previous photo",
    next: "Next photo",
    captions: [
      "A warm welcome on Turufjell",
      "The main-floor living room",
      "Gather around the table",
      "The terrace",
      "Room for everyone",
      "The main-floor sauna",
      "A place to rest",
      "Winter on Turufjell",
      "Mountain biking on Turufjell",
    ],
    comfortLabel: "A LITTLE MORE CABIN COMFORT",
    comfortTitle: "Make yourself at home.",
    comforts: [
      ["Ski from the doorstep", "The cross-country trail begins outside the cabin, and the alpine area is approximately 150 metres away by ski – no car needed."],
      ["Warm up after a day out", "Two saunas, underfloor heating and firewood for the fireplace. Settle in after a day in the mountain air."],
      ["Meals worth lingering over", "Two kitchens, with dining space for 14–16 on the main floor and 26–28 on the lower floor."],
      ["Bring the team", "Room for meetings, workshops and team retreats, with broadband and spacious shared areas."],
    ],
    amenities: ["Wi-Fi", "Parking", "4 dishwashers", "Washing machine", "TV", "Barbecue", "Cot and high chair"],
    seasonsLabel: "ONE MOUNTAIN. FOUR SEASONS.",
    seasonsTitle: "A little closer to nature.",
    winter: "Days on the slopes",
    winterText: "Head out on the cross-country trails or take the family to the ski slopes. Stop at the slope-side café before coming home to the fire.",
    summer: "Trails and mountain air",
    summerText: "Explore the trails towards Kristnatten, try the pumptrack or find a quiet fishing lake. There’s plenty to keep you outdoors.",
    locationLabel: "CLOSER THAN YOU THINK",
    locationTitle: "A mountain escape.\nUnder two hours from Oslo.",
    locationText: "On the sunny side of Turufjell, in Flå in Hallingdal, the cabin overlooks the mountain landscape. Flå village, shops and Bjørneparken wildlife park are around a 15-minute drive away.",
    transport: "You can also take the train to Flå and a taxi up to the cabin. There’s plenty of parking at the property, with EV charging by the café near the ski lift.",
    practical: "Good to know",
    practicalItems: [
      ["How many guests can stay?", "The cabin sleeps up to 29 across nine bedrooms and a sleeping alcove in the loft. See FINN for the room layout and details."],
      ["What about linen and cleaning?", "Bed linen and towels can be arranged on request. Final cleaning is mandatory. See the FINN listing for current charges and terms."],
      ["Can we bring pets?", "Pets and smoking are not allowed. The cabin is not wheelchair accessible."],
      ["How do we enquire?", "Visit our FINN listing to see available dates, prices and rental terms, and contact the host there."],
    ],
    endLabel: "YOUR NEXT MOUNTAIN GETAWAY",
    endTitle: "Good memories\nstart here.",
    endText: "Pick a weekend. Bring your favourite people. Find available dates and send an enquiry on FINN.",
    endCta: "Check availability on FINN",
    footer: "A cabin for the moments that matter.",
    source: "Details and photos from our FINN listing.",
  },
};
